import utils

# Container (mm and kg)
CONTAINER_WIDTH = 2682.1
CONTAINER_HEIGHT = 3200.2
CONTAINER_DEPTH = 10332.2
CONTAINER_LOAD = 26480

# Pallet (mm and kg)
PALLET_WIDTH = 2500
PALLET_DEPTH = 1000
PALLET_HEIGHT = CONTAINER_HEIGHT - 145  # 145 is the height of the pallet itself
PALLET_LOAD = 2490
PALLET_DIMS = utils.Dimension(PALLET_WIDTH, PALLET_DEPTH, PALLET_HEIGHT, PALLET_LOAD)

# Product dimension ranges (mm and kg)
NUM_PRODUCTS = 36
MIN_PRODUCT_WIDTH = 50
MAX_PRODUCT_WIDTH = PALLET_WIDTH
MIN_PRODUCT_DEPTH = 50
MAX_PRODUCT_DEPTH = PALLET_DEPTH
MIN_PRODUCT_HEIGHT = 50
MAX_PRODUCT_HEIGHT = PALLET_HEIGHT
MIN_PRODUCT_WEIGHT = 2
MAX_PRODUCT_WEIGHT = PALLET_LOAD

# Numpy
RANDOM_SEED = 42
